@startuml class-uml
rectangle Article {
    interface Article {
        + id(): string
        + categoryId(): string
        + title(): string
        + content(): string
        + slug(): string
        + isPublic(): bool
    }
    class PublicArticle {
        - id: Id
        - categoryId: Id
        - title: string
        - content: string
        - slug: string
        - mainImgUrl: ?string

        + mainImgUrl(): ?string
    }
    class DraftArticle {

    }
    interface ArticleRepository {
        store(Article $article): void
    }
    class ArticleDbRepository {

    }

    Article <|-- PublicArticle
    Article <|-- DraftArticle
}

rectangle Validator {
    class Validator {
        - originals: array
        - rules: array

        + validate(): void
        + isPass(): bool
        + errors(): ValidateErrors
    }
    note top: バリデーションを実施し、エラーがあればエラーメッセージを取得

    interface Rule {
        + pass($value): bool
        + errorMessage(): string
    }
    note top: バリデーションルールを実施

    Rule <|-- RequiredRule

    class ValidateErrors {
        - errors: array<errorItem:string, messages:array<string>>
        + addError(string $key, string $message)
    }
    note bottom: エラーメッセージを管理

    Validator "1" *-- "0 .. n" Rule
    Validator "1" ..|> "0 .. 1" ValidateErrors
}

@enduml
